import { useState } from 'react';
import { Archive, Download, Trash2, Search, FileText, Share2, Copy, X } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { formatDistanceToNow } from 'date-fns';
import api from '../../services/api';
import toast from 'react-hot-toast';

const TYPE_COLORS: Record<string, string> = {
  MARKDOWN: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
  TEXT:     'bg-slate-500/10 text-slate-400 border-slate-500/20',
  JSON:     'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
  CODE:     'bg-green-500/10 text-green-400 border-green-500/20',
  CSV:      'bg-amber-500/10 text-amber-400 border-amber-500/20',
  REPORT:   'bg-violet-500/10 text-violet-400 border-violet-500/20',
  DATA:     'bg-orange-500/10 text-orange-400 border-orange-500/20',
};

export default function ArtifactsPage() {
  const qc = useQueryClient();
  const [search, setSearch] = useState('');
  const [shareModal, setShareModal] = useState<any>(null);
  const [typeFilter, setTypeFilter] = useState('');
  const [preview, setPreview] = useState<any>(null);


  const shareArtifact = useMutation({
    mutationFn: ({ id, expiresInDays }: { id: string; expiresInDays?: number }) =>
      api.post(`/artifacts/${id}/share`, { expiresInDays }),
    onSuccess: (res) => {
      setShareModal({ ...shareModal, ...res.data.data });
      toast.success('Share link created');
    },
  });

  const revokeShare = useMutation({
    mutationFn: (id: string) => api.delete(`/artifacts/${id}/share`),
    onSuccess: () => { toast.success('Share link revoked'); setShareModal(null); qc.invalidateQueries({ queryKey: ['artifacts'] }); },
  });
  const { data, isLoading } = useQuery({
    queryKey: ['artifacts', typeFilter],
    queryFn: async () => {
      const p = new URLSearchParams({ limit: '50' });
      if (typeFilter) p.append('type', typeFilter);
      const { data } = await api.get(`/artifacts?${p}`);
      return data.data;
    },
  });

  const deleteArtifact = useMutation({
    mutationFn: (id: string) => api.delete(`/artifacts/${id}`),
    onSuccess: () => { toast.success('Deleted'); qc.invalidateQueries({ queryKey: ['artifacts'] }); },
  });

  const API_URL = import.meta.env.VITE_API_URL || '/api';
  const artifacts = (data?.artifacts || []).filter((a: any) =>
    !search || a.name?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="font-display text-2xl font-bold text-white">Artifacts</h1>
          <p className="text-slate-400 text-sm mt-0.5">{data?.total ?? 0} files generated by agents</p>
        </div>
      </div>

      <div className="flex gap-3 mb-5 flex-wrap">
        <div className="relative flex-1 min-w-[200px]">
          <Search size={14} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" />
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search artifacts..."
            className="forge-input pl-9 text-sm py-2.5" />
        </div>
        <div className="flex gap-2 flex-wrap">
          {['', 'MARKDOWN', 'TEXT', 'JSON', 'CODE', 'CSV', 'REPORT'].map(t => (
            <button key={t} onClick={() => setTypeFilter(t)}
              className={`text-xs px-3 py-2 rounded-lg border transition-all ${typeFilter === t
                ? 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30'
                : 'bg-white/[0.03] border-white/[0.08] text-slate-400 hover:text-slate-200'}`}>
              {t || 'All'}
            </button>
          ))}
        </div>
      </div>

      {preview && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setPreview(null)}>
          <div className="forge-card w-full max-w-2xl max-h-[80vh] overflow-hidden" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06]">
              <h3 className="font-medium text-white truncate">{preview.name}</h3>
              <button onClick={() => setPreview(null)} className="text-slate-400 hover:text-white text-sm px-3 py-1 rounded-lg hover:bg-white/5">Close</button>
            </div>
            <div className="p-5 overflow-y-auto max-h-[60vh]">
              <pre className="text-xs text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">{preview.content?.substring(0, 5000)}</pre>
            </div>
          </div>
        </div>
      )}

      {isLoading ? (
        <div className="space-y-3">{[...Array(4)].map((_,i)=><div key={i} className="forge-card h-16 animate-pulse" />)}</div>
      ) : artifacts.length === 0 ? (
        <div className="forge-card p-12 text-center">
          <Archive size={32} className="text-indigo-400 mx-auto mb-4" />
          <p className="text-slate-300 font-medium mb-2">No artifacts yet</p>
          <p className="text-slate-500 text-sm">Agents generate artifacts (reports, code, data) automatically during task execution</p>
        </div>
      ) : (
        <div className="space-y-2.5">
          {artifacts.map((a: any) => (
            <div key={a._id} className="forge-card-hover px-4 py-3.5 flex items-center gap-4">
              <FileText size={16} className="text-indigo-400 flex-shrink-0" />
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium text-slate-200 truncate">{a.name}</p>
                  <span className={`status-badge border text-xs flex-shrink-0 ${TYPE_COLORS[a.type] || TYPE_COLORS.TEXT}`}>{a.type}</span>
                </div>
                <div className="flex items-center gap-3 mt-0.5">
                  <p className="text-xs text-slate-500">{(a.size / 1024).toFixed(1)} KB</p>
                  <p className="text-xs text-slate-600">{formatDistanceToNow(new Date(a.createdAt), { addSuffix: true })}</p>
                  {a.downloadCount > 0 && <p className="text-xs text-slate-600">{a.downloadCount} downloads</p>}
                </div>
              </div>
              <div className="flex items-center gap-1.5 flex-shrink-0">
                <button onClick={() => setPreview(a)}
                  className="p-2 text-slate-500 hover:text-slate-300 hover:bg-white/5 rounded-lg transition-all text-xs">
                  Preview
                </button>
                  <button onClick={() => setShareModal(a)}
                  className="p-2 text-slate-500 hover:text-indigo-400 hover:bg-indigo-500/10 rounded-lg transition-all"
                  title="Share">
                  <Share2 size={14} />
                </button>
         <a href={`${API_URL}/artifacts/${a._id}/download?token=${localStorage.getItem('accessToken') || ''}`}
  target="_blank"
  rel="noreferrer"
  className="p-2 text-slate-500 hover:text-indigo-400 hover:bg-indigo-500/10 rounded-lg transition-all">
  <Download size={14} />
</a>
                <button onClick={() => { if(confirm('Delete?')) deleteArtifact.mutate(a._id); }}
                  className="p-2 text-slate-500 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-all">
                  <Trash2 size={14} />
                </button>
              </div>
            </div>
          ))}



      {/* Share modal */}
      {shareModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setShareModal(null)}>
          <div className="forge-card w-full max-w-md p-6" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-display font-bold text-white flex items-center gap-2">
                <Share2 size={16} className="text-indigo-400" /> Share Artifact
              </h3>
              <button onClick={() => setShareModal(null)} className="text-slate-500 hover:text-slate-300"><X size={18} /></button>
            </div>

            <p className="text-sm text-slate-400 mb-4">{shareModal.name}</p>

            {shareModal.shareUrl ? (
              <>
                <div className="flex items-center gap-2 bg-white/[0.05] border border-white/[0.1] rounded-lg px-3 py-2.5 mb-4">
                  <input
                    readOnly
                    value={`${window.location.origin}${shareModal.shareUrl}`}
                    className="flex-1 bg-transparent text-xs text-slate-300 outline-none"
                  />
                  <button
                    onClick={() => { navigator.clipboard.writeText(`${window.location.origin}${shareModal.shareUrl}`); toast.success('Copied!'); }}
                    className="text-indigo-400 hover:text-indigo-300"
                  >
                    <Copy size={14} />
                  </button>
                </div>
                {shareModal.expiresAt && (
                  <p className="text-xs text-slate-500 mb-4">Expires {new Date(shareModal.expiresAt).toLocaleDateString()}</p>
                )}
                <button
                  onClick={() => revokeShare.mutate(shareModal._id)}
                  className="forge-btn-secondary w-full text-sm text-red-400 border-red-500/20"
                >
                  Revoke Link
                </button>
              </>
            ) : (
              <div className="space-y-3">
                <button
                  onClick={() => shareArtifact.mutate({ id: shareModal._id })}
                  className="forge-btn-primary w-full text-sm"
                  disabled={shareArtifact.isPending}
                >
                  Create Permanent Link
                </button>
                <button
                  onClick={() => shareArtifact.mutate({ id: shareModal._id, expiresInDays: 7 })}
                  className="forge-btn-secondary w-full text-sm"
                  disabled={shareArtifact.isPending}
                >
                  Create Link (Expires in 7 days)
                </button>
              </div>
            )}
          </div>
        </div>
      )}

        </div>

      )}
    </div>
  );
}
